### ISSUE TITLE
Channel number

### ISSUE THREAD

**Issue by Miniz199922** [Threadfin/Threadfin#118]
With telly you can use  tvg-chno="431" in m3u to assign channel numbers can this be done with threadfin?

**Comment by Fyb3roptik** [comment]
You can use a custom filter to bring all channels in as they are

**Comment by Miniz199922** [comment]
Can you please explain how to

**Comment by Fyb3roptik** [comment]
Choose custom filter and set it to this

```
{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}
```

**Comment by Deihmos** [comment]
You will have to change to tvg-id=xx. Threadfun does not recognize tvg-chno.

**Comment by Miniz199922** [comment]
> Choose custom filter and set it to this
> 
> ```
> {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}
> ```

I tried this and its not working

**Comment by air360** [comment]
@Fyb3roptik 
Hey Nick,
.....i was looking on here trying to figure out why when i added my m3u which already has the channel numbers preset it just defaulted to 1000+. I found where you mentioned the custom filter and that did not seem to do anything. Then I saw the comment above by @Deihmos about Threadfin not recognizing tvg-chno and i think that may be my issue.  Looking at my m3u details they are formatted like this:

#EXTINF:-1 tvg-id="mychannel.us" tvg-name="MyChannel" tvg-logo="MyChannelLogoURL.us.png" tvg-chno="275" channel-id="275" group-title="Network TV",MyChannel

So i think, based on this and based on the comment by @Deihmos my issue is the channel number is defined in tvg-chno and not in the tvg-id.

Is it at all possible to have Threadfin look for or recognize tvg-chno as the channel number or maybe even a way to define which to look for in settings?  Maybe a variable that we could choose which tag to look for the channel number from (basically we select either tvg-id or tvg-chno ?  

Either way, thanks for taking on this project.  Xteve was always awesome and super stable, but Threadfin just feels like xteve being modernized. I love it!

**Comment by air360** [comment]
> 

wow, that was the fastest reply in the history of replies LOL. 

Let me provide the motivation and idea behind this (and maybe others) just for the full picture. I, personally, am not trying to have 1000 channels that I do not always watch. What I (and i assume others) have found really awesome and a good way to do it is to go through and basically replicate the lineup of a "commercial provider" by matching channel numbers to the network, etc etc.  Then when you add that to plex or whatever your player is you can simply choose that "commercial provider" for your guide data and since your channel numbers and everything looks identical, it provides you 100% full and complete guide data at all times.  so what I actually put into xteve/threadfin is basically a replica lineup of what a full provider would look like.  Then if there are other alternative channels I want i can add those as another m3u and handle them separately.

**Comment by Fyb3roptik** [comment]
Well when xteve was created it was where you would do that. Can I ask why not use the mapping in threadfin to set the channels? Curious as to why you don't just use that since I fixed a ton of xteve issues with it

**Comment by air360** [comment]
Of course. as well all know, Plex can be a bit clunky and it is actually not my main player. I use an Apple TV frontend app called Channels DVR that also has a backend "server" that manages it all.  It was specifically designed for managing HDHomeRun players.  Last year they began accepting M3U files as a source as well instead of just physical HDHR.  I used to run through xteve with my m3u files to create the HDHR and then into the software, but once they began accepting M3U files I was able to preformat my M3U and add it directly....which, when i would add it in to that it basically was plug and play and would load up and be ready to go right out of the gate, so the core need for xteve was no longer needed and i was able to directly use my m3u in my main player.

I have never given up on plex though, and I have always loved xteve as my organizer for channels outside that "main lineup" that was already formatted a specific way.

I also like redundancies, so if something on my main setup went down, I could flip over to plex and be good to go in the meantime...so I have still tried to keep a mirror setup on xteve(threadfin).  

So to be honest. its more of a convenience of having the channel numbers match out the gate because it would allow me to easily use threadfin to maintain both my "preformatted lineup" and my custom lineup in one app.

You are not wrong though, I could send all through threadfine, and maybe i should.....

**Comment by enz1ey** [comment]
I know this is an old thread, but I'd like to reiterate what @air360 is saying. I have about 300 channels across three IPTV providers, sometimes I make changes to my M3U to use different providers for different channels for various reasons. Sometimes I have to delete the entire thing and start over.

In either case, this results in having to manually change anywhere from dozens to hundreds of channel numbers in Threadfin, and there's no (obvious) easy way to do it. These channels are already numbered correctly on the M3U, though (I use IPTVBoss and pipe it to Channels DVR, which is where Threadfin pulls from). I think at least having an option in Threadfin to use the channel ID/number on the M3U would be great.

**Comment by 2fst4u** [comment]
Definitely chiming in with the same desire. My source m3us have the numbers I want and then bringing them into threadfin they all start in the thousands. I'd definitely prefer the numbering would be retained.

**Comment by jld341** [comment]
I would also like to have this option as I use another service to pull channel numbers to match to my local area so this would be very helpful option.  For now, I understand I can go through and update but it woul dbe a nice option
