### ISSUE TITLE
Bulk assign EPG to channels

### ISSUE THREAD

**Issue by dausruddin** [Threadfin/Threadfin#218]
**Is your feature request related to a problem? Please describe.**
After adding EPGs, I had to assign them to each channel one by one. It maps channel to ID automatically after I selected the EPG I added.

**Describe the solution you'd like**
 Probably would be great if I can bulk assign all channel to a particular EPG and it would automatically map the ID.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Fyb3roptik** [comment]
More than likely the tvg-id didnt match the channel id in the EPG. Check to make sure those match up

**Comment by reitermiller** [comment]
Can confirm that on latest docker version channels are not being automatically mapped despite accurate tvg-id declaration, requiring the user to painstakingly set the XMLTV File for each individual channel before the ID is automatically picked up. It would be great if the bulk edit function that's present in Xteve could work to change this, or at least for there to be a default/fallback XMLTV file selection option in the settings.

**Comment by Uuugh** [comment]
I'm having the same problem with automap not working. I'm using Threadfin in Docker with "Pluto for Channels" and "Samsung TV Plus".

I tested the Pluto and Samsung playlists & EPGs in Emby and all automapped (in Emby) but they won't automap in Threadfin.

To be fair, Pluto paired in Threadfin the first time I set up the Docker Stack... but I was experimenting with setups so I deleted the stack and volumes, and repeated my setup with a new stack. (I take notes in order to ensure I use the same settings.)

Automap has not worked since.

`services:
  pluto-for-channels: # http://192.168.0.160:8080/ 
    container_name: pluto-for-channels
    image: jonmaddox/pluto-for-channels
    ports:
      - 8080:80  # http://127.0.0.1:8080/playlist.m3u    http://127.0.0.1:8080/epg.xml
    environment:
      TZ: America/New_York
      PUID: 1030
      PGID: 100
      #VERSIONS: Pluto1,Pluto2
      START: 10000
    volumes:
      - /mnt/docker/config/pluto-for-channels:/config
    restart: unless-stopped
  samsung-tvplus: # http://192.168.0.160:8182/
    container_name: samsung-tvplus
    image: matthuisman/samsung-tvplus-for-channels
    ports:
      - 8182:80
    environment:
      # REGIONS: us|gb # at,ca,ch,de,es,fr,gb,in,it,kr,us
      TZ: America/New_York
      PUID: 1030
      PGID: 100
    restart: unless-stopped
  threadfin: # http://192.168.0.160:34400/web/ 
    image: fyb3roptik/threadfin # :1.2.25
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      PUID: 1030
      PGID: 100
      TZ: America/New_York
    volumes:
      - /mnt/docker/config/threadfin:/home/threadfin/conf
      - /mnt/docker/data/threadfin/temp:/tmp/threadfin:rw
      - /mnt/docker/data/xmltv:/home/threadfin/xmltv
    restart: unless-stopped
`

Open the Control Panel http://192.168.0.160:34400/web/ 
Settings
- Automatic update of Threadfin:	Enabled
- SSDP:				Enabled
- Number of Tuners:		3	
- EPG Source:			XEPG
- Enable Default Dummy Data:	Enabled
- Dummy Data Channel:		PPV
- Schedule for updating (Playlist, XMLTV, Backup):	0000,0600,1200,1800
- Updates all files at startup:		Enabled
- Image Caching:			Enabled
- WEB Authentication:		Enabled
- Create user:		*****
	> Save

Playlist > New > Type: M3U
Name: 		Pluto:8080				Samsung Tvplus:8182
Description:	
M3U File:	http://192.168.0.160:8080/playlist.m3u	http://192.168.0.160:8182/playlist.m3u8?regions=us&start_chno=20000
Buffer:		FFmpeg
Tuner / Streams:	3
> Save

XMLTV > New
Name:		Pluto:8080				Samsung Tvplus:8182
Description:
XMLTV File:	http://192.168.0.160:8080/epg.xml		http://192.168.0.160:8182/epg.xml?regions=us&start_chno=20000
> Save
Filter > New
	Type:		Threadfin: Custom Filter
	Filter Name: 	Excluded
Description:
Case Sensitive:	Disabled

(I tried mapping to Dummy and the actual XML... below is just one of my attempts)
Mapping > Bulk Edit > Set all to active, Threadfin Dummy, and clear the xmltv channel
automatic… but channel info can be modified here as well as assigning backup channels.
Streaming URLs: 

Playlist (Emby, Jellyfin): 	http://192.168.0.160:34400/m3u/threadfin.m3u
EPG (all): 		http://192.168.0.160:34400/xmltv/threadfin.xml

Thanks!
